{('EV_SYN', 0): [('SYN_REPORT', 0), ('SYN_CONFIG', 1), ('SYN_DROPPED', 3), ('?', 4), ('?', 21)],
 ('EV_KEY', 1): [(['BTN_A', 'BTN_GAMEPAD', 'BTN_SOUTH'], 304), (['BTN_B', 'BTN_EAST'], 305),
                 (['BTN_NORTH', 'BTN_X'], 307), (['BTN_WEST', 'BTN_Y'], 308), ('BTN_TL', 310), ('BTN_TR', 311),
                 ('BTN_TL2', 312), ('BTN_TR2', 313), ('BTN_SELECT', 314), ('BTN_START', 315), ('BTN_MODE', 316),
                 ('BTN_THUMBL', 317), ('BTN_THUMBR', 318)],
 ('EV_ABS', 3): [(('ABS_X', 0), AbsInfo(value=126, min=0, max=255, fuzz=0, flat=15, resolution=0)),
                 (('ABS_Y', 1), AbsInfo(value=124, min=0, max=255, fuzz=0, flat=15, resolution=0)),
                 (('ABS_Z', 2), AbsInfo(value=0, min=0, max=255, fuzz=0, flat=15, resolution=0)),
                 (('ABS_RX', 3), AbsInfo(value=122, min=0, max=255, fuzz=0, flat=15, resolution=0)),
                 (('ABS_RY', 4), AbsInfo(value=133, min=0, max=255, fuzz=0, flat=15, resolution=0)),
                 (('ABS_RZ', 5), AbsInfo(value=0, min=0, max=255, fuzz=0, flat=15, resolution=0)),
                 (('ABS_HAT0X', 16), AbsInfo(value=0, min=-1, max=1, fuzz=0, flat=0, resolution=0)),
                 (('ABS_HAT0Y', 17), AbsInfo(value=0, min=-1, max=1, fuzz=0, flat=0, resolution=0))],
 ('EV_MSC', 4): [('MSC_SCAN', 4)],
 ('EV_FF', 21): [(['FF_EFFECT_MIN', 'FF_RUMBLE'], 80), ('FF_PERIODIC', 81), (['FF_SQUARE', 'FF_WAVEFORM_MIN'], 88),
                 ('FF_TRIANGLE', 89), ('FF_SINE', 90), (['FF_GAIN', 'FF_MAX_EFFECTS'], 96)]}
